### ISSUE TITLE
Feature Request: Duration to equal the length of the audio/video file

### ISSUE THREAD

**Issue by KyleBurger** [zhw2590582/WFPlayer#10]
It looks like the duration has a max of 100. I'm curious if there's a way to make the duration be the entire length of the audio or video file?

**Comment by zhw2590582** [comment]
Duration means the length of time displayed on each screen, not the length of video. If the duration of a video is one hour, I can't render it in one screen at a time, so I set the maximum value of 100

**Comment by KyleBurger** [comment]
Could you have an offset property that takes the duration of the video and renders the wave length based on the offset. So instead of going second by second, if you had an offset of 3 for example it would render the wave every 3 seconds instead?

**Comment by zhw2590582** [comment]
Do you mean interval rendering? For example `1~3`、`6~9`、`12~15` render only?
