### ISSUE TITLE
Add a scroll or pan option 

### ISSUE THREAD

**Issue by larrywal** [zhw2590582/WFPlayer#11]
I'd like to be able to have the user be able to scroll or panDrag through the waveform to help them find a location they'd like to seek to.  Easy to add as an option?

**Comment by zhw2590582** [comment]
If there is scroll or pan, it means that the waveform needs to render larger size. For example, I have to prepare 0-10 and 20-30 views for my view in 10-20 seconds. This will be a bit complicated. Do you understand what I mean

**Comment by larrywal** [comment]
Yes I do understand.  I'm ok with that since I need the functionality - similar to Adobe Premiere or Audacity if you've used those.  The user is designing something to synchronize with the music, so need to be able to jump back and forth.

And perhaps if it's an issue for performance, if the user scrolls too fast, you could just leave it blank or drop showing some of the peaks and let it catch up as it can.  (just brainstorming)

**Comment by zhw2590582** [comment]
I understand what you said. The functions you want can also be implemented, but it needs more time to optimize. But at present, I am still busy with other work and have no time to maintain this library. I need to implement the functions you want later. I'm very sorry

**Comment by larrywal** [comment]
Thanks much completely understand and no worries.  FWIW maybe easy to just load the whole file all at once and not worry about the loading logic?  Maybe it'd be too much memory.  Anyway, appreciate the answers!
