### ISSUE TITLE
Is there any way to load waveform from JSON data generated on a server for larger files of around 2GB or more?

### ISSUE THREAD

**Issue by bugcoder** [zhw2590582/WFPlayer#15]
Is there any way to load waveform from JSON? Like  passing URL of JSON file or API returning JSON data for waveform:

wf.load(document.querySelector('#video')); //adding support of JSON data as well here along with media URL and element.

The same support is provided by:
Wavesurfer (https://wavesurfer-js.org/)
https://wavesurfer-js.org/faq/
https://github.com/bbc/audiowaveform

Actually, the browser is getting crash whenever we are passing the URL of a larger video file. Also, when are passing chunks from the server waveform is generating for the first chunk only.

**Comment by zhw2590582** [comment]
Yes, actually `wf.load` method can be loaded [AudioBuffer](https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer)，Or you can parse the PCM data for audio on the server, such as using [web-audio-api](https://github.com/audiojs/web-audio-api)，Then the front-end loads PCM data through Ajax and simulates it as [AudioBuffer](https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer), In one of my personal projects, that's how it works：

Node.js：
```js
const fs = require('fs');
const { AudioContext } = require('web-audio-api');
const context = new AudioContext();

context.decodeAudioData(fs.readFileSync('/path/to/audio.mp3'), (audiobuffer) => {
    // choose your channel
    const channelData = audiobuffer.getChannelData(0);
    fs.writeFileSync('/path/to/audio.pcm', channelData);
});
```

browser：
```js
fetch('/path/to/audio.pcm')
    .then((res) => res.arrayBuffer())
    .then((buffer) => {
        wf.load({
            sampleRate: 44100,
            getChannelData() {
                return new Float32Array(buffer);
            },
        });
    });
```

**Comment by salmanAhmad143** [comment]
@zhw2590582 I am doing the same and trying to load pcm file using wf.load() like above you have mentioned-

`fetch('http://localhost:3000/images/standard-captions.pcm')
    .then((res) => res.arrayBuffer())
    .then((buffer) => {
        this.wf.load({
            sampleRate: 44100,
            getChannelData() {
                return new Float32Array(buffer);
            },
        });
    });`


 But it showing me error that -
> "The load target is not a string. If you are loading a mediaElement, make sure the mediaElement.src is not empty."

I think this is due to this:

`load(target) {
        if (target instanceof HTMLVideoElement || target instanceof HTMLAudioElement) {
            this.options.mediaElement = target;
            target = target.src;
        }
        errorHandle(
            **typeof target === 'string' && target.trim(),**
            `The load target is not a string. If you are loading a mediaElement, make sure the mediaElement.src is not empty.`,
        );
        this.loader.load(target);
        this.emit('load');
        return this;
    }`

Please suggest where i am doing wrong?

Thanks

**Comment by zhw2590582** [comment]
I forgot to release the latest version, you now try to install the latest version: `wfplayer@1.1.4`

**Comment by salmanAhmad143** [comment]
Hi @zhw2590582 ,

Thanks for your reply. I have updated wfplayer@1.1.4 version at my end and now the error not showing but the wave not been generating. Only a thin line is drawing in the timeline area. If i am increasing sampleRate value then length of line has been increasing but still wave not generating. See below-

![timeline](https://user-images.githubusercontent.com/17023890/111997041-a3f76780-8b40-11eb-8265-7dc105a18fed.PNG)

This is buffer array that i am passing in load() function-

![arrayBuffer](https://user-images.githubusercontent.com/17023890/111997613-3ac42400-8b41-11eb-94a2-e6d3d95a7c63.PNG)

I am creating .pcm from .mp4 file using ffmpeg. Please suggest what i am making wrong?

Thanks,

**Comment by zhw2590582** [comment]
In fact, WFPlayer does not yet support PCM files generated by `ffmpeg`,  I found that the PCM data generated by `ffmpeg` and the PCM data generated by `AudioContext` are very different. I have not found a compatible method, so I suggest you use [web-audio-api](https://github.com/audiojs/web-audio-api) to generate PCM data.

```js
const fs = require('fs');
const { AudioContext } = require('web-audio-api');
const context = new AudioContext();

context.decodeAudioData(fs.readFileSync('/path/to/audio.mp3'), (audiobuffer) => {
    // choose your channel
    const channelData = audiobuffer.getChannelData(0);
    fs.writeFileSync('/path/to/audio.pcm', channelData);
});
```
