### ISSUE TITLE
Waveform of large audio files

### ISSUE THREAD

**Issue by MugenTrip** [zhw2590582/WFPlayer#19]
Hello, I have tried your program for short audio files  (10-20 seconds) and it is working fine. You have done really amazing job, thank you very much. But I need the waveform of large audio files (20min-2hours). Unfortunately, even if I use a 20min audio file, the memory explodes. Am I doing something wrong or this waveform generator is not for so large files?

**Comment by zhw2590582** [comment]
https://github.com/zhw2590582/WFPlayer#common-problem

**Comment by MugenTrip** [comment]
Thank you for your fast reply. The file I use is not a video, it is an audio (wav) file. Should I reduce its size to avoid the memory explosion?

**Comment by zhw2590582** [comment]
yes
