### ISSUE TITLE
Is there a way to remove the padding entirely?

### ISSUE THREAD

**Issue by miles352** [zhw2590582/WFPlayer#21]
The padding on the left and right is getting annoying because it is a different color than the background. Why can't I set padding below 1 in the options? I would like to completely remove it.
![image](https://user-images.githubusercontent.com/76878501/141598563-67bb1b29-3edb-4eba-8e32-abfe4faf1605.png)

**Comment by zhw2590582** [comment]
You can set the color to be fully transparent：`rgba(0,0,0,0)`

**Comment by miles352** [comment]
How would I change the color of the padding? I already have the backgroundColor set to fully transparent

**Comment by zhw2590582** [comment]
`paddingColor`

**Comment by miles352** [comment]
Thank you, I should have tried that.
