### ISSUE TITLE
error:  Uncaught (in promise) DOMException: Unable to decode audio data 

### ISSUE THREAD

**Issue by MerinAlex23** [zhw2590582/WFPlayer#25]
I can see the grid and the ruler is moving but cannot see the waves.

**Comment by zhw2590582** [comment]
How big is your audio file, you can open your audio file directly on this website [wfplayer.js.org](https://wfplayer.js.org/)

**Comment by MerinAlex23** [comment]
It's just 4 seconds long..

**Comment by zhw2590582** [comment]
If it is convenient, you can upload your audio file directly to issues, or send it to my mailbox, I will help you to see

**Comment by MerinAlex23** [comment]
Thanks very much. I have shared the audio file via mail.
