### ISSUE TITLE
preload option availability

### ISSUE THREAD

**Issue by LijaAlex12** [zhw2590582/WFPlayer#26]
Is there a possibility of removing the delay while the waveform is being generated, as the audio in my case is fetched from server.
The audio is playing but the the waveform corresponding to the first 2 beats is delayed.
I have added preload="auto" to audio tag.

**Comment by zhw2590582** [comment]
I don't understand what you mean. Is there have a time delay between the audio and waveform?
Like, audio in 3s but the waveform in 1s?
