### ISSUE TITLE
jump to point in time?

### ISSUE THREAD

**Issue by larrywal** [zhw2590582/WFPlayer#3]
I want to control which part of the waveform is in view based on outside factors, and I want to do this when the audio is not currently playing.  

I tried using wf.seek(time) to set the specific time I want in view but that doesn't auto scroll the view to a timecode that is outside of the duration currently shown.  (it does if the audio is playing).

Can someone help me please?  How do I scroll a specific timecode into view when the audio is not playing?

**Comment by zhw2590582** [comment]
Hello, you're right, this is a bug and has been fixed in `1.1.0`.

**Comment by larrywal** [comment]
Thanks very much - I'll take a look.  As a different question, I'd really like to be able to show a duration longer than 100 seconds.  I'm working with audio files 20-30 minutes long.  Is there a reason you don't let me zoom out that far?  I don't mind at all losing resolution on the wave form, but I need to be able to support that length so I can synchronize the timeline with a different control that has timings throughout the 30 minutes.

**Comment by zhw2590582** [comment]
If it is greater than 100, the text on the ruler will appear crowded, so I don't want to let go of this restriction for the time being.

But you can modify the limit value yourself:

https://github.com/zhw2590582/WFPlayer/blob/ffeefd1a59e1f34d9581c63478ed4b7d2fbe2ef8/src/index.js#L88

**Comment by larrywal** [comment]
Thanks - will try modifying the limit.  As an aside, since it already
appears I can turn the ruler on and off, would it be easy to either
paramatrize or automatically calculate the granularity for the ruler?

E.g. even if I'm at duration 100 for 1000 pixels it overlaps badly.  Seems
like the desired behavior would always be to back off and show fewer tick
marks....

Thoughts?

**Comment by zhw2590582** [comment]
Suppose the duration of 100 seconds is displayed in 1000 pixels, and the padding is 0. I will divide each second into 10 columns, which is why the ruler is so crowded.

Total number of columns is `1000 = 100 * 10 + 0 * 2`

The pixel of each column is `1px = 1000px / 1000`

This is obviously unreasonable, but there is currently no option to control the number of columns per second, but your suggestion is correct, I want to think about an optimized solution.

**Comment by larrywal** [comment]
I noticed you closed this, but I don't see it fixed?

**Comment by larrywal** [comment]
@zhw2590582  any thoughts?  I am hoping I don't need to go to a different control.

**Comment by zhw2590582** [comment]
After a long time, I don't know what kind of question you asked. Can you ask it again, thank you very much

**Comment by larrywal** [comment]
Lol no problem - When I'm zoomed out I'd like the labels to be less granular so they don't overlap.  See your comment from Feb 11.  Does that help?  Happy to brainstorm with you.

**Comment by zhw2590582** [comment]
You want to make sure that the ruler and text are not crowded together when the rendering time is very long, such as 200 seconds, right?

**Comment by larrywal** [comment]
Correct.  Or even longer ideally - could be up to 1200-1500 seconds (at which point you could imagine just rendering a label every 60 seconds or something.

**Comment by larrywal** [comment]
As an example, look at how the labels work in the timeline control here (use the mouse wheel to zoom in and out).  This lets you zoom all the way from months to milliseconds.

https://visjs.github.io/vis-timeline/examples/timeline/groups/verticalItemsHide.html

**Comment by zhw2590582** [comment]
I see what you mean. Let the ruler adjust the density automatically according to the duration. This can be achieved

**Comment by larrywal** [comment]
Fantastic!  Very excited to see!
