### ISSUE TITLE
Need help with setting up the subtitles on the waveform

### ISSUE THREAD

**Issue by NinjaCoderDotCom** [zhw2590582/WFPlayer#32]
So, I need to add some subtitles to my waveform shown as in the screenshot attached below. In the following screenshot, I am using wfplayer version 1.1.4. I recently updated the wfplayer version to 2.1.3. To calculate the subtitle position according to the grid, I was using two values: this.wf.drawer.gridGap and this.wf.options.pixelRatio. Can you please tell me where I can find these values? Have you changed the path to these values or removed them? If yes, then in wfplayer version 2.1.3, how do you calculate subtitle position?

![wavefrom](https://user-images.githubusercontent.com/107407402/196184588-673fcb8d-0e41-4db8-8f01-2352cc6a0423.png)

**Comment by zhw2590582** [comment]
In `wfplayer@2.2.0` version, it can be found in `wf.drawer.config`
