### ISSUE TITLE
+1h audio file destroys the ram

### ISSUE THREAD

**Issue by ExtReMLapin** [zhw2590582/WFPlayer#43]
Hello, even with 32gb of ram, it fills up on chrome and firefox when  I use a 1h30 audio **WAV** file

![Taskmgr_PgUsXqMMZW](https://user-images.githubusercontent.com/3909752/233094241-641bcbb6-f413-44e2-94b8-1b1329780f82.png)

**Comment by ExtReMLapin** [comment]
I know the description states with video but here it's already audio, but in WAV format, is it an issue ?

**Comment by zhw2590582** [comment]
You can see this: https://github.com/zhw2590582/WFPlayer/issues/39#issuecomment-1362828204

**Comment by ExtReMLapin** [comment]
I'll stick to mp3 file, that'll be easier
