### ISSUE TITLE
Could you please add a speed-changing function?

### ISSUE THREAD

**Issue by newproplus** [zhw2590582/WFPlayer#47]
I'm going to make a player like **music speed changer** which is a good music player.
For now, WFPlayer nearly has all the functions I want, except a speed-changing function. In my opinion, it might be called like `wf.seek(second);`

Thank you for your great job.

**Comment by zhw2590582** [comment]
You can set the playbackRate of mediaElement, and the waveform will be synchronized to this speed

**Comment by newproplus** [comment]
OK, thank you very much. Maybe adding this to the document is more helpful.
