### ISSUE TITLE
adding grab_start and grab_end events

### ISSUE THREAD

**Issue by VeloeEvall** [zhw2590582/WFPlayer#51]
Hi. I'd love to have grabbing_start and grabbing_end events added to pause my audio during the time i'm holding mouse, because now when i stop moving mouse it plays my audio.
I'm not using html tag, I've created audio in js code.

**Comment by zhw2590582** [comment]
you can do this

```js
wf.on('mousedown', () => {
// grabbing_start 
});

wf.on('mousemove', () => {
// grabbing
});

wf.on('mouseup', () => {
// grabbing_end 
});
```

**Comment by VeloeEvall** [comment]
Ah yeah, sorry I didn't see that. Thanks a lot!
