### ISSUE TITLE
Appending custom headers

### ISSUE THREAD

**Issue by gregorio-disco** [zhw2590582/WFPlayer#54]
Is there a way to attach custom headers to the `fetch` that WFPlayer does to the audio resource?

If not, how can I access protected media elements?

**Comment by zhw2590582** [comment]
Like this:

```js
fetch('path/to/audio.mp3', {
    headers: {}
})
    .then((res) => res.arrayBuffer())
    .then((arrayBuffer) => {
        const uint8 = new Uint8Array(arrayBuffer);
        wf.load(uint8);
    });
```

**Comment by gregorio-disco** [comment]
Thank you! Doing this fetch wouldn't create two requests?
