### ISSUE TITLE
npm run dev 报错无法运行

### ISSUE THREAD

**Issue by huanghaiyang** [zhw2590582/WFPlayer#58]
node v18.16.1报错如下：

`> wfplayer@2.2.8 dev
> npx cross-env NODE_ENV=development node ./scripts/dev.mjs

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: Unable to open snapshot file: No such file or directory]

Node.js v18.16.1`

node 16.14.0报错如下：
`> wfplayer@2.2.8 dev
> npx cross-env NODE_ENV=development node ./scripts/dev.mjs

node:v8:345
  der.readHeader();
      ^

Error: Unable to deserialize cloned data due to invalid or unsupported version.
    at deserialize (node:v8:345:7)
    at deserialize (D:\work\github\WFPlayer\node_modules\@parcel\core\lib\serializer.js:204:48)
    at getAndDeserialize (D:\work\github\WFPlayer\node_modules\@parcel\core\lib\RequestTracker.js:853:42)`

请问本地应该用哪个版本的node才可以？

**Comment by zhw2590582** [comment]
可以试试通过yarn来安装依赖

**Comment by huanghaiyang** [comment]
通过修改scripts/dev.mjs文件，发现是如下代码报错：

bundler.watch(async (error, event) => {
        if (error) throw error;
        if (event.type === 'buildSuccess') {
            const bundles = event.bundleGraph.getBundles();
            console.log(`✨ Built ${bundles.length} bundles in ${event.buildTime}ms!`);
            if (!isOpenBrowser) {
                isOpenBrowser = true;
                openBrowser(url);
            }
        } else if (event.type === 'buildFailure') {
            console.log(event.diagnostics);
        }
    });

npm run dev时可以忽略上面的错误，因为应用程序已经启动，可以通过localhost:8083访问！
