### ISSUE TITLE
Could you open source the demo website?

### ISSUE THREAD

**Issue by rockcs1992** [zhw2590582/WFPlayer#6]
Hi,

Thank you for making the library. I think the library will be very useful for something I'm building now. Is it possible that you could show me the source code of your demo page so that I could better understand how to use it?

Thanks!

**Comment by rockcs1992** [comment]
If you don't feel comfortable about that, could you tell me why there is not waveform displayed in this sample sandbox? Thanks for your help
https://codesandbox.io/s/elegant-sky-dexru

**Comment by rockcs1992** [comment]
If you don't feel comfortable doing that, could you take a look at this simple demo and tell me what is wrong with it and how to make it work? Thank you so much!
https://codesandbox.io/s/elegant-sky-dexru

**Comment by zhw2590582** [comment]
The code is here: https://github.com/zhw2590582/WFPlayer/tree/master/docs

**Comment by rockcs1992** [comment]
I see. Thank you!
