### ISSUE TITLE
External source for audio file

### ISSUE THREAD

**Issue by LauraPiccolo** [zhw2590582/WFPlayer#7]
Hi,
I am trying to generate a player from an audio that has an external source as in the following example:

`<audio id="audio" src='https://bucketeer-a2765e62-ceca-4f5b-9eba-dcfd3a02354e.s3.amazonaws.com/public/motherfucouer/1.mp3' type="audio/mpeg" />`

The audio source is playing, and the player is generated but the waves won't create themselves.
I checked an it works (the waves appear) with a local file. Do you have an explanation and/or a solution for me?

Thank you!

**Comment by zhw2590582** [comment]
Please open the console to see if there are any errors reported, most likely because of cross-domain issues

**Comment by LauraPiccolo** [comment]
There are no errors reported. As I told you the audio file is loaded properly, and I am able to play it ...
If there is a cross-domain issue related to WFPlayer it's not visible in the console.

**Comment by zhw2590582** [comment]
I tested it, you need to add cors option:

```js
var wf = new WFPlayer({
  container: document.querySelector("#waveform"),
  cors: true
});
```
